id = "csharp_roslyn"
name = "C# (Roslyn)"
description = "C# support via OmniSharp-Roslyn & netcoredbg"
version = "0.2.0"
schema_version = 1
authors = ["Marc Peters <marc@peters.casa>"]
repository = "https://github.com/marcptrs/csharp-roslyn"

[settings]
enable_debug_logging = { 
  description = "Enable debug logging for troubleshooting. Add to LSP settings under initialization_options.", 
  type = "boolean", 
  default = false 
}

[[capabilities]]
kind = "process:exec"
command = "find"
args = ["*", "-name", "*", "-type", "f"]

[language_servers.omnisharp-roslyn]
name = "OmniSharp-Roslyn"
language = "CSharp"

[debug_adapters.netcoredbg]

[debug_locators.dotnet]

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
rev = "6303e406f61d8bac254da178963a8f2f3041ad87"
